### ISSUE TITLE
Add Skillet shopping list to Farming Bar[REQUEST]

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farming-bar#1]
Feature Request:

There's an addon called Skillet where you can create a shopping list of items to complete from objectives (Like 5 armor kits, 2 bandages).

This may be a reach but is there a way that one could 1-click the items in Skillet's shopping list (which can be accessed by clicking on Skillet's "Shopping List" button) and add them to Farming Bar?  If there was a list already in Farming Bar, this would be added on.  Perhaps it would be easier for you if it were a separate bar, that's up to you of course.

The alternative was an addon called Jigsaw by jjsheets but that one died in Vanilla and was never converted to Classic.  That addon was a crafting interface but had it's own tracker.

If this can't be done, I understand.  This is already more than I could ever hope as it is :)

**Comment by niketa-wow** [comment]
I've been working on a rewrite for a bit and one of my planned new features is a sort of advanced objective. As I'm still working on rewriting the existing functionality, I haven't gotten to implementing this quite yet, so it's a good time to get your feedback on how you'd like it to function for when I do start on that part.

My plan is to have a way to create an advanced objective tracker that you could drag onto the bar, where you could set up different items and how you wanted to track it. For example, if I need 300 herbs, but they can be different types of herbs, I want you to be able to set up an advanced objective that counts all of the herbs to track the total. Or, and I'm assuming this is what you're looking for, say you want to craft a specific item, you should be able to set it up so the objective tracks each item needed to craft it and it notifies you when you have all the materials.

Since I don't use Skillet myself, I'd have to say implementing that would have to be a bit down the line, but I do plan on adding what I think you're looking for. For the base, is there a particular way you'd like to see something like this implemented? 

I'm thinking a certain section in the options to set up the different rules of the objective, then just an icon that can be dragged from there onto your bar. How would you like to see the announcements for it?

Example:
Say I want to track what I need to make a cauldron, from just the flowers. I'd name the custom tracker "Cauldron".
I'd need:

240 Zin'anthid, 60 Anchor Weed, 15 Star Moss, 15 Siren's Pollen, 15 Sea Stalk, 15 Riverbud

Say I have nothing and gain 5 Zin'anthid, should it say:
a) 5/360 Cauldron
b) 5/240 Zin'anthid (5/360 Cauldron)
c) 5/360 Cauldron (5/240 Zin'anthid 0 Anchor Weed 0 Star Moss 0 Siren's Pollen 0 Sea Stalk 0 Riverbud)
d) Something else??

Anyway, sorry if this is asking a bit much. I was gonna work something else out on my own, but if this is what you were looking for anyway, having extra input would help me create something that's easy to use and read for everyone.

**Comment by rbpaiett** [comment]
No problem, everything from now on is a plus.  I hacked that other addon but it was barely working as it was.  I like how the base working so far.  The only change I made was when you gain an item on your list, I use the sound when the auction interface opens instead of the coin clinking one, but that's just my own personal preference.

**Comment by niketa-wow** [comment]
Shouldn't be hard for me to add the ability to change sounds. I'm adding the use of Ace3 in the rewrite, so it'd be very simple to select a different sound.
