### ISSUE TITLE
Single Item Shopping List

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farming-bar#11]
With the Darkmoon Faire, there are sometimes a list of crafted items that can be turned in for tickets.  Occasionally it calls for a number of crafted items that need only one type of material.  For the sake of organization I need a 1 item shopping list (e.g.: 7 Heavy Grinding Stones needing only Heavy Stones).

A shopping list that can be created with one type of material. (single-item shopping list)

I can just list an item slot but it doesn't have a description that can be edited (e.g.: Darkmoon Heavy Grinding Stones (7)) 
-- Perhaps an alternative might be to have the option to be able to assign/edit a title to single item type slots like you can with a shopping list.

**Comment by niketa-wow** [comment]
I think single item shopping lists kind of defeat the purpose of them, but I don't think it'd be too difficult to add a title option for it, especially since there's already the ability to edit or add items with the objective builder. 

For your alerts, how would you like it to display the item (%n)? As the item name or the title (obviously item name when there is no title).

Or would you like to see an additional placeholder (%t) to get the title of the item. So for an item it would return the title if any and if it's a shopping list or mixed items it would return nothing because %n already returns their titles. 

Would you like to see this implemented with currencies as well or items only? I think.maybe this wouldn't be too relevant to you as you play classic actually but I would still like your feedback on that. Not sure when the last time you played retail was, but if you could recall any point where you wanted to farm a currency (honor, valor, etc) and think naming it would be useful.

**Comment by niketa-wow** [comment]
To clarify what I meant with the new placeholder, here's an example:

Format:
Farming progress: %n (%t) %d

Alert:
Heavy Grinding Stone (Darkmoon Faire) +3

**Comment by rbpaiett** [comment]
I didn't do much farming for currencies but that would be helpful.  That alert you have listed there would work just fine.

I just want a list of all materials and their target numbers, but separately I want to list all the items they would craft and their numbers.  Sort of a shopping list with a sub-shopping list.

**Comment by niketa-wow** [comment]
I've gotten a title implemented for items. I decided against doing it for currencies either because I'm lazy or there was a reason it sounded redundant to me that I forgot.

Anyway, I'm gonna leave this here to help out:

%n%if("%t", (%t),)if%

This will display the name of the objective (like normal) and if there's an item title it will show the title in parentheses. %t only works for item titles. Mixed Items and Shopping list titles will still fall under %n.

This change will be implemented in version 2.1 which I hope to have released soon.
